# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/casbin_util.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/casbin_util.proto\"5\n\x0eUserPermission\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\npermission\x18\x02 \x01(\t\",\n\x08UserRole\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07role_id\x18\x02 \x01(\t\"\x14\n\x04Rule\x12\x0c\n\x04rule\x18\x01 \x01(\t\"\x19\n\x06RoleId\x12\x0f\n\x07role_id\x18\x01 \x01(\t\"\x19\n\x06UserId\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x0f\n\rEmptyResponse\"%\n\x0cVerifyResult\x12\x15\n\rverify_result\x18\x01 \x01(\x08\"P\n\x12PermissionResponse\x12$\n\x03row\x18\x01 \x03(\x0b\x32\x17.PermissionResponse.Row\x1a\x14\n\x03Row\x12\r\n\x05items\x18\x01 \x03(\t\"\x1b\n\nStringList\x12\r\n\x05items\x18\x01 \x03(\t2\xed\x02\n\nCasbinUtil\x12+\n\x07\x65nforce\x12\x0f.UserPermission\x1a\r.VerifyResult\"\x00\x12&\n\x0cgetRolesUser\x12\x07.UserId\x1a\x0b.StringList\"\x00\x12*\n\x0b\x61\x64\x64RoleUser\x12\t.UserRole\x1a\x0e.EmptyResponse\"\x00\x12\"\n\x07\x61\x64\x64Rule\x12\x05.Rule\x1a\x0e.EmptyResponse\"\x00\x12-\n\x0e\x64\x65leteRoleUser\x12\t.UserRole\x1a\x0e.EmptyResponse\"\x00\x12\'\n\ndeleteRole\x12\x07.RoleId\x1a\x0e.EmptyResponse\"\x00\x12)\n\x0e\x64\x65leteRoleMenu\x12\x05.Rule\x1a\x0e.EmptyResponse\"\x00\x12\x37\n\x15getPermissionByUserId\x12\x07.UserId\x1a\x13.PermissionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.casbin_util_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERPERMISSION']._serialized_start=28
  _globals['_USERPERMISSION']._serialized_end=81
  _globals['_USERROLE']._serialized_start=83
  _globals['_USERROLE']._serialized_end=127
  _globals['_RULE']._serialized_start=129
  _globals['_RULE']._serialized_end=149
  _globals['_ROLEID']._serialized_start=151
  _globals['_ROLEID']._serialized_end=176
  _globals['_USERID']._serialized_start=178
  _globals['_USERID']._serialized_end=203
  _globals['_EMPTYRESPONSE']._serialized_start=205
  _globals['_EMPTYRESPONSE']._serialized_end=220
  _globals['_VERIFYRESULT']._serialized_start=222
  _globals['_VERIFYRESULT']._serialized_end=259
  _globals['_PERMISSIONRESPONSE']._serialized_start=261
  _globals['_PERMISSIONRESPONSE']._serialized_end=341
  _globals['_PERMISSIONRESPONSE_ROW']._serialized_start=321
  _globals['_PERMISSIONRESPONSE_ROW']._serialized_end=341
  _globals['_STRINGLIST']._serialized_start=343
  _globals['_STRINGLIST']._serialized_end=370
  _globals['_CASBINUTIL']._serialized_start=373
  _globals['_CASBINUTIL']._serialized_end=738
# @@protoc_insertion_point(module_scope)
