# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.utils.casbin_grpc.protos import casbin_util_pb2 as protos_dot_casbin__util__pb2


class CasbinUtilStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.enforce = channel.unary_unary(
                '/CasbinUtil/enforce',
                request_serializer=protos_dot_casbin__util__pb2.UserPermission.SerializeToString,
                response_deserializer=protos_dot_casbin__util__pb2.VerifyResult.FromString,
                )
        self.getRolesUser = channel.unary_unary(
                '/CasbinUtil/getRolesUser',
                request_serializer=protos_dot_casbin__util__pb2.UserId.SerializeToString,
                response_deserializer=protos_dot_casbin__util__pb2.StringList.FromString,
                )
        self.addRoleUser = channel.unary_unary(
                '/CasbinUtil/addRoleUser',
                request_serializer=protos_dot_casbin__util__pb2.UserRole.SerializeToString,
                response_deserializer=protos_dot_casbin__util__pb2.EmptyResponse.FromString,
                )
        self.addRule = channel.unary_unary(
                '/CasbinUtil/addRule',
                request_serializer=protos_dot_casbin__util__pb2.Rule.SerializeToString,
                response_deserializer=protos_dot_casbin__util__pb2.EmptyResponse.FromString,
                )
        self.deleteRoleUser = channel.unary_unary(
                '/CasbinUtil/deleteRoleUser',
                request_serializer=protos_dot_casbin__util__pb2.UserRole.SerializeToString,
                response_deserializer=protos_dot_casbin__util__pb2.EmptyResponse.FromString,
                )
        self.deleteRole = channel.unary_unary(
                '/CasbinUtil/deleteRole',
                request_serializer=protos_dot_casbin__util__pb2.RoleId.SerializeToString,
                response_deserializer=protos_dot_casbin__util__pb2.EmptyResponse.FromString,
                )
        self.deleteRoleMenu = channel.unary_unary(
                '/CasbinUtil/deleteRoleMenu',
                request_serializer=protos_dot_casbin__util__pb2.Rule.SerializeToString,
                response_deserializer=protos_dot_casbin__util__pb2.EmptyResponse.FromString,
                )
        self.getPermissionByUserId = channel.unary_unary(
                '/CasbinUtil/getPermissionByUserId',
                request_serializer=protos_dot_casbin__util__pb2.UserId.SerializeToString,
                response_deserializer=protos_dot_casbin__util__pb2.PermissionResponse.FromString,
                )


class CasbinUtilServicer(object):
    """Missing associated documentation comment in .proto file."""

    def enforce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getRolesUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addRoleUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteRoleUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteRoleMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPermissionByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CasbinUtilServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'enforce': grpc.unary_unary_rpc_method_handler(
                    servicer.enforce,
                    request_deserializer=protos_dot_casbin__util__pb2.UserPermission.FromString,
                    response_serializer=protos_dot_casbin__util__pb2.VerifyResult.SerializeToString,
            ),
            'getRolesUser': grpc.unary_unary_rpc_method_handler(
                    servicer.getRolesUser,
                    request_deserializer=protos_dot_casbin__util__pb2.UserId.FromString,
                    response_serializer=protos_dot_casbin__util__pb2.StringList.SerializeToString,
            ),
            'addRoleUser': grpc.unary_unary_rpc_method_handler(
                    servicer.addRoleUser,
                    request_deserializer=protos_dot_casbin__util__pb2.UserRole.FromString,
                    response_serializer=protos_dot_casbin__util__pb2.EmptyResponse.SerializeToString,
            ),
            'addRule': grpc.unary_unary_rpc_method_handler(
                    servicer.addRule,
                    request_deserializer=protos_dot_casbin__util__pb2.Rule.FromString,
                    response_serializer=protos_dot_casbin__util__pb2.EmptyResponse.SerializeToString,
            ),
            'deleteRoleUser': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteRoleUser,
                    request_deserializer=protos_dot_casbin__util__pb2.UserRole.FromString,
                    response_serializer=protos_dot_casbin__util__pb2.EmptyResponse.SerializeToString,
            ),
            'deleteRole': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteRole,
                    request_deserializer=protos_dot_casbin__util__pb2.RoleId.FromString,
                    response_serializer=protos_dot_casbin__util__pb2.EmptyResponse.SerializeToString,
            ),
            'deleteRoleMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteRoleMenu,
                    request_deserializer=protos_dot_casbin__util__pb2.Rule.FromString,
                    response_serializer=protos_dot_casbin__util__pb2.EmptyResponse.SerializeToString,
            ),
            'getPermissionByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.getPermissionByUserId,
                    request_deserializer=protos_dot_casbin__util__pb2.UserId.FromString,
                    response_serializer=protos_dot_casbin__util__pb2.PermissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CasbinUtil', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CasbinUtil(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def enforce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CasbinUtil/enforce',
            protos_dot_casbin__util__pb2.UserPermission.SerializeToString,
            protos_dot_casbin__util__pb2.VerifyResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getRolesUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CasbinUtil/getRolesUser',
            protos_dot_casbin__util__pb2.UserId.SerializeToString,
            protos_dot_casbin__util__pb2.StringList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addRoleUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CasbinUtil/addRoleUser',
            protos_dot_casbin__util__pb2.UserRole.SerializeToString,
            protos_dot_casbin__util__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CasbinUtil/addRule',
            protos_dot_casbin__util__pb2.Rule.SerializeToString,
            protos_dot_casbin__util__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteRoleUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CasbinUtil/deleteRoleUser',
            protos_dot_casbin__util__pb2.UserRole.SerializeToString,
            protos_dot_casbin__util__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CasbinUtil/deleteRole',
            protos_dot_casbin__util__pb2.RoleId.SerializeToString,
            protos_dot_casbin__util__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteRoleMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CasbinUtil/deleteRoleMenu',
            protos_dot_casbin__util__pb2.Rule.SerializeToString,
            protos_dot_casbin__util__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getPermissionByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CasbinUtil/getPermissionByUserId',
            protos_dot_casbin__util__pb2.UserId.SerializeToString,
            protos_dot_casbin__util__pb2.PermissionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
