from marshmallow import fields
from app.controllers.response.response_schema import ResponseSchema


class PsTaskDetail(ResponseSchema):
    project_id = fields.Int(metadata={"label": "项目ID"})
    task_id = fields.Str(metadata={"label": "任务ID"})
    task_start_date = fields.DateTime('%Y-%m-%d %H:%M:%S', metadata={"label": "开始日期"})
    task_end_date = fields.DateTime('%Y-%m-%d %H:%M:%S', metadata={"label": "结束日期"})
    task_owner = fields.Str(metadata={"label": "任务负责人"})
    external = fields.Dict(metadata={"label": "支持总结"})
    is_pass = fields.Bool(metadata={"label": "是否通过预检"})
    report_file_id = fields.Str(metadata={"label": "导出报告文件"})
    project_subject = fields.Str(metadata={"label": "项目名称"})
    project_account = fields.Str(metadata={"label": "客户名称"})
    project_owner = fields.Str(metadata={"label": "项目负责人"})
    task_subject = fields.Str(metadata={"label": "任务标题"})
    inspection_type = fields.Str(metadata={"label": "巡检类型"})
    contrast = fields.Bool(metadata={"label": "季度对比"})


class PsTaskUploadHistoryDetail(ResponseSchema):
    id = fields.Str(metadata={"label": "ID"})
    upload_file_id = fields.Str(metadata={"label": "上传文件历史ID"})
    file_name = fields.Str(metadata={"label": "文件名称"})
    created_by_date = fields.DateTime('%Y-%m-%d %H:%M:%S', metadata={"label": "创建时间"})
    delete_by_date = fields.DateTime('%Y-%m-%d %H:%M:%S', metadata={"label": "删除时间"})
    upload_file_url = fields.Str(metadata={"label": "文件下载地址"})
    subject = fields.Str(metadata={"label": "主题"})
    count = fields.Int(metadata={"label": "数量"})
    city = fields.Str(metadata={"label": "落地城市"})
    area = fields.Str(metadata={"label": "部署区域"})
    account_id = fields.Str(metadata={"label": "客户ID"})
    account_name = fields.Str(metadata={"label": "客户名称"})


class PsTaskUploadHistoryList(ResponseSchema):
    list = fields.List(fields.Nested(PsTaskUploadHistoryDetail(unknown="exclude")))
    total_use = fields.Int(allow_none=True)
    total = fields.Int(allow_none=True)


class PsTaskCustomerArchives(ResponseSchema):
    id = fields.Str(metadata={"label": "ID"})
    task_id = fields.Str(metadata={"label": "上传文件历史ID"})
    city = fields.Str(metadata={"label": "落地城市"})
    account_id = fields.Str(metadata={"label": "客户ID"})
    account_name = fields.Str(metadata={"label": "客户名称"})
    area = fields.Str(metadata={"label": "部署区域"})
    device_name = fields.Str(metadata={"label": "设备名称"})
    device_model = fields.Str(metadata={"label": "设备型号"})
    device_sn = fields.Str(metadata={"label": "SN"})
    ha_state = fields.Str(metadata={"label": "HA状态"})
    software_version = fields.Str(metadata={"label": "软件版本"})
    uptime = fields.Str(metadata={"label": "运行时间"})
    feature = fields.Str(metadata={"label": "开启功能"})
    plat_expiration = fields.Str(metadata={"label": "许可证有效期"})
    session_info = fields.Str(metadata={"label": "并发会话/最大会话"})
    alloc_session = fields.Str(metadata={"label": "新建会话"})
    cur_cpu = fields.Str(metadata={"label": "CPU利用率"})
    cp_memory = fields.Str(metadata={"label": "CP利用率"})
    dp_memory = fields.Str(metadata={"label": "DP利用率"})
    throughput = fields.Str(metadata={"label": "整机吞吐"})
    ps_status = fields.Str(metadata={"label": "电源状态"})
    fan_status = fields.Str(metadata={"label": "风扇状态"})
    module_status = fields.Str(metadata={"label": "板卡状态"})
    env_cpu_temperature = fields.Str(metadata={"label": "模块温度"})
    snat_rate = fields.Str(metadata={"label": "SNAT使用率"})
    dnat_rate = fields.Str(metadata={"label": "DNAT使用率"})
    address_rate = fields.Str(metadata={"label": "地址簿使用率"})
    server_rate = fields.Str(metadata={"label": "服务簿使用率"})
    policy_rate = fields.Str(metadata={"label": "策略使用率"})
    alg_status = fields.Str(metadata={"label": "ALG状态"})
    ha_status_info = fields.Str(metadata={"label": "HA状态信息"})
    log_folder = fields.Str(metadata={"label": "日志开启状态"})
    attack_info = fields.Str(metadata={"label": "攻击信息"})
    exception_log_info = fields.Str(metadata={"label": "异常日志信息"})
    clock = fields.Str(metadata={"label": "巡检时间"})
    original_manager = fields.Str(metadata={"label": "原厂负责人"})
    account_manager = fields.Str(metadata={"label": "客户负责人"})
    contact_info = fields.Str(metadata={"label": "联系方式"})
    purchase_date = fields.Str(metadata={"label": "购买时间"})
    online_date = fields.Date(metadata={"label": "上线时间"}, format="%Y-%m-%d")
    created_by_id = fields.Str(metadata={"label": "创建人"})
    created_by_date = fields.DateTime(metadata={"label": "创建时间"}, format="%Y-%m-%d %H:%M:%S")
    status = fields.Str(metadata={"label": "状态"})
    is_publish = fields.Str(metadata={"label": "是否发布"})
    tip = fields.List(fields.Str(), metadata={"label": "提示信息"})
    lic_expiration_time = fields.Date(metadata={"label": "过期时间"}, format="%Y-%m-%d")
    route_entry = fields.Str(metadata={"label": "路由条目使用率"})
    machine_room = fields.Str(metadata={"label": "机房位置"})
    inspection_type = fields.Str(metadata={"label": "巡检类型"})
    date_tag = fields.Str(metadata={"label": "巡检标签"})
    date_tag_label = fields.Str(metadata={"label": "时间描述"})


class PsTaskCustomerArchivesList(ResponseSchema):
    list = fields.List(fields.Nested(PsTaskCustomerArchives(unknown="exclude")))

